export const initialTools = [
  {
    name: "Netfox",
    category: "Local network",
    description: "A native macOS monitor that shows connected devices, their history, and network alerts.",
    howTo: "Install the app, grant the required permissions, then open Devices: name the devices you recognise and review any new ones.",
    href: "https://netfox.app/",
    image: "/tools/netfox-cover.png",
    badge: "macOS",
  },
  {
    name: "urlscan.io",
    category: "URL analysis",
    description: "A web sandbox for seeing what a link actually loads before opening it in your browser.",
    howTo: "Paste the URL and choose the scan visibility carefully; then review the screenshot, requests, domains, and detected IPs.",
    href: "https://urlscan.io/",
    image: "/tools/urlscan.png",
    badge: "Web",
  },
  {
    name: "crt.sh",
    category: "DNS & certificates",
    description: "Searches Certificate Transparency logs, making it useful for discovering subdomains associated with a domain.",
    howTo: "Search for %example.com, replacing example.com with an authorised domain; filter the results and verify the relevant entries.",
    href: "https://crt.sh/",
    image: "/tools/crt.png",
    badge: "Web",
  },
  {
    name: "CyberChef",
    category: "Data analysis",
    description: "A browser-based lab for decoding, converting, and inspecting data without writing a script.",
    howTo: "Paste your input, find an operation such as From Base64, and drag it into the Recipe: the output updates instantly.",
    href: "https://gchq.github.io/CyberChef/",
    image: "/tools/data-cover.png",
    badge: "Web",
  },
  {
    name: "Password Cracker",
    category: "Password security",
    description: "A project by lfazioli for exploring password strength and password-security concepts in a controlled environment.",
    howTo: "Use it only with passwords, hashes, or test data you own or are explicitly authorised to assess; start with a safe sample and review the result.",
    href: "https://password-cracker-pearl.vercel.app/",
    image: "/tools/pwd.png",
    badge: "Your project",
  },
  {
    name: "SpiderFoot",
    category: "OSINT",
    description: "Automates the collection and correlation of public information for an initial asset map.",
    howTo: "Run it locally, create a scan for a target you own, and start with the core modules; always validate results manually.",
    href: "https://github.com/smicallef/spiderfoot",
    image: "/tools/osint-cover.png",
    badge: "Open source",
  },
  {
    name: "DNSDumpster",
    category: "Reconnaissance",
    description: "A quick view of a domain's public DNS relationships, useful for getting oriented during an assessment.",
    howTo: "Enter a domain you own or are authorised to assess, and use the map as a starting point—not as a definitive source.",
    href: "https://dnsdumpster.com/",
    image: "/tools/dns-cover.png",
    badge: "Web",
  },
{"name": "Wireshark", "category": "Local network", "description": "Capture and inspect network traffic with an open-source protocol analyser.", "howTo": "Select your network interface, capture traffic from your own lab, then use display filters to inspect the packets.", "href": "https://www.wireshark.org/", "image": "", "badge": "Open source"},
{"name": "Nmap", "category": "Reconnaissance", "description": "Discover hosts and services to understand the exposure of a network.", "howTo": "Install Nmap and start with host discovery on your own lab network, then review the hosts and services found.", "href": "https://nmap.org/", "image": "", "badge": "Open source"},
{"name": "VirusTotal", "category": "URL analysis", "description": "Look up reports on files, URLs, domains, and IP addresses from multiple security sources.", "howTo": "Search for a file hash or URL to read existing reports. Review detections and relationships together before drawing conclusions.", "href": "https://www.virustotal.com/", "image": "", "badge": "Web"},
{"name": "Shodan", "category": "OSINT", "description": "Search public information about Internet-connected devices and exposed services.", "howTo": "Search for your own public IP or organisation, then review the indexed services and banners.", "href": "https://www.shodan.io/", "image": "", "badge": "Web"}
];
